version: '3.8'

services:
  mysql:
    image: mysql:8.0 
    container_name: mysql_proy
    restart: always 
    environment: 
      MYSQL_USER : usermysql
      MYSQL_ROOT_PASSWORD : password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: proyecto
    ports:
      - '33066:3306'
    volumes: 
      - mysql_vol:/var/lib/mysql
    networks:
      - clone_trello

  app:
    container_name: application
    build: 
      dockerfile: Dockerfile
      context: . 
    command: uvicorn app.main:app --reload --port 8011
    ports:
      - 8010:8011

    environment:
      DB_URL: mysql://usermysql:password@localhost:33066/proyecto
    volumes:
      - .:/usr/src/app
    networks:
      - clone_trello

  worker:
    container_name: worker_celery
    build: 
      dockerfile: Dockerfile
      context: .
    command: celery -A celery_app:celery worker
    volumes:
      - .:/usr/src/app
    environment:
      CELERY_BROKER_URL: amqp://user:mypass@rabbitmq:5671//
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      - rabbitmq
    networks:
      - clone_trello

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5671:5672
      - 15672:15672
    networks:
      - clone_trello

  # flower:
  #   image: mher/flower
  #   environment:
  #     - CELERY_BROKER_URL= amqp://user:mypass@rabbitmq:5672/
  #     - FLOWER_PORT=8888
  #   ports:
  #     - 8888:8888
      
  #   depends_on:
  #     - rabbitmq
  #     - worker

volumes:
  mysql_vol:

networks:
  clone_trello:
    external: true
