version: '3.8'

services:
  app:
    container_name: application
    restart: always
    build: 
      dockerfile: docker/Dockerfile
      context: .. 
    command: uvicorn app.main:app --reload --port 8000 --host 0.0.0.0
    ports:
      - '8000:8000'
    environment:
      DB_URL: 'mysql://usermysql:password@mysql:3306/proyecto'
    volumes:
      - ../:/usr/src/app/
    networks:
      - clone_trello
  
  worker:
    container_name: worker_celery
    restart: always 
    build: 
      dockerfile: docker/Dockerfile
      context: ..
    command: celery -A app.worker.celery_app:celery worker 
    volumes:
      - ..:/usr/src/app
    environment:
      CELERY_BROKER_URL: amqp://user:mypass@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    networks:
      - clone_trello

networks:
  clone_trello:
    external: true
