version: '3.8'

services:
  mysql:
    image: mysql:8.0 
    container_name: mysql_proy
    restart: always 
    environment: 
      MYSQL_USER : usermysql
      MYSQL_ROOT_PASSWORD : password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: proyecto
    ports:
      - '33066:3306'
    volumes: 
      - mysql_vol:/var/lib/mysql
    networks:
      - clone_trello

  app:
    container_name: application
    build: 
      dockerfile: docker/Dockerfile
      context: .. 
    command: uvicorn app.main:app --reload --port 8000 --host 0.0.0.0
    ports:
      - '8000:8000'
    environment:
      DB_URL: 'mysql://usermysql:password@mysql:3306/proyecto'
    volumes:
      - ../:/usr/src/app/
    networks:
      - clone_trello
  
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - '5672:5672'
      - '15672:15672'

    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: mypass
    networks:
      - clone_trello

  worker:
    container_name: worker_celery
    build: 
      dockerfile: docker/Dockerfile
      context: ..
    command: celery -A app.worker.celery_app:celery worker
    volumes:
      - ..:/usr/src/app
    environment:
      CELERY_BROKER_URL: amqp://user:mypass@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      - rabbitmq
    networks:
      - clone_trello



  flower:
    image: mher/flower
    environment:
      CELERY_BROKER_URL: amqp://user:mypass@rabbitmq:5672/
      FLOWER_PORT: 8888
    ports:
      - 8888:8888
      
    depends_on:
      - rabbitmq
      - worker

volumes:
  mysql_vol:

networks:
  clone_trello:
    external: true
